# Generated by Django 3.1.2 on 2020-10-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messagerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('user1', models.CharField(max_length=50)),
                ('user2', models.CharField(max_length=50)),
            ],
        ),
    ]
