# Generated by Django 3.1.2 on 2020-10-12 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerie',
            name='objectOfMessage',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
