# Generated by Django 3.1.2 on 2020-10-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_messagerie_objectofmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerie',
            name='objectOfMessage',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
