# Generated by Django 3.1.2 on 2020-10-12 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201012_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerie',
            name='objectOfMessage',
            field=models.CharField(default='No title', max_length=50),
        ),
    ]
