# Generated by Django 3.1.2 on 2020-10-12 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_auto_20201012_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagerie',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='messagerie',
            name='user2',
        ),
        migrations.AddField(
            model_name='messagerie',
            name='id_user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='messagerie',
            name='id_user2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
